### PR TITLE
Update non-active Fasting GlanceView

### PR DESCRIPTION
**Pull request by axl13**
- Unified the look while fasting and not.
- Add time since last fast as "Elapsed"
- Move "Streak" count to the tile line

IMG_20200610_081542

### CODE REVIEW

**Comment by axl13** [comment]
Testing now. 
Still need to update localization.
Not sure why the diff is so big, there isn't that many changes.

**Comment by pyrob2142** [comment]
Hi Oleksiy,
that's a great idea. Just yesterday I received feedback in this direction:

> Is it possible to integrate:
after a fasting phase, to start optional an eating phase?  For example, after 16 hours of fastingtime, for example 8 hours of eating timer.

My problem with this was that there isn't really a way for the widget to "wake-up" once the eating window passes, to start a new fast and notify the user. It's really a shame that we can't set reliable background timers for widgets. Your solution is a great alternative to having a timer and I will integrate it in the widget as well, the idea being to switch the layout of the streak view depending on if a fast is active or not. If no fast is active the streak is displayed smaller and shifted to the top, to make space for the time elapsed since the last fast ended in the lower half of the screen, with the streak being a bit bigger so it retains the focus. I think that could work well and hope to have a working implementation by tomorrow or the day after, depending on my spare time.

About the view: 
One thing I'm not sure about is "FASTED" as a label. In my experience the word "fast" and its verbs are complicating localization, as some languages like German don't even have a proper noun for it. We have the nominalization "das Fasten", which is why the whole "nominalization: y/n" shenanigans in the translation sheet exist. As stupid as it sounds given the context of the widget, but in order to keep localization as simple as possible I try to limit the occurrence or the word "fast" as much as possible, since languages handle it so differently. 
I'm thinking about displaying "Streak" on the top left, so the number on the top right has some context and maybe change "elapsed" to something like "Since" because of the following semantics: I would read "Streak 20 since 36h 30m" meaning my streak has not improved since 36h 30m, so maybe I should start working on it again. This would work because as soon as a fast is started the view switches to the active fast anyway. The obvious bonus would be that we already have the strings for that in the resources and I think it would work great with the idea of streak goals (see below).

Another thing is to make this feature optional in the settings (but, as I did with your stacked colors, on by default, so people notice it), so users who don't want to be guilt tripped into fasting by their watch can have a choice. 

That empty bar also gave me the idea of letting users set a streak goal in the settings, so they have some long time goal to work towards to. Setting it to 0 disables the feature and will hide the bar and the ring in streak view, setting it to anything else will display it similar to how the fast progress works, but with a much simpler logic - no thresholds. Neutral blue bar / ring until you reach it, turns green if you do. Maybe a little firework animation once you reach it, similar to what Garmin does once you reach your daily step goal. The streak text could read "20/100", if the feature is active. If the goal is reached it could be simply doubled to have a new goal to work towards (the user can overwrite it anyway, just to give some automation to the guys who don't look into settings). 

What are your thoughts on these points?

Just a little heads up: I'm currently pretty much in the middle of my finals for this term and sleep is turning into something precious, so me responding and integrating stuff slower than usual, doesn't mean I don't like it. I just have to juggle uni, work and this stuff. I'm sorry for that and hope you understand. I've skimmed over the code and hope to have it merged either today or tomorrow!

Thanks again for a great idea and contribution to the project!

**Comment by axl13** [comment]
Thank you!

Sorry for late reply. Busy at work. I will look into notification scheduler
:)

Feel free to modify my code to fit better your ideas. I'm cool.

I am really liking how it coming toning together!

Have a great day,
  Oleksiy

**Comment by pyrob2142** [comment]
Absolutely no problem, I'm quite busy too, so I fully understand.

Regarding the scheduler: Travis Vitek (a Garmin dev) said on the dev forum
multiple times that this is not possible, I think the time since last
feature is the best solution. Some guy even tried a hack using calendar
events and alarms, but that didn't work either. If you find a solution /
workaround to that problem a lot of Garmin devs will love you as this is a
feature that's been requested for years.

I think I have the GlanceView done (just testing right now, will push later
this evening), now I just have to incorporate all the new features into the
widget itself and make sure everything shares the same design language.
Hopefully I can deploy the update tomorrow after some more testing in the
sim.

Really thanks for your input. The glance view wouldn't look like it does
without you! :)

All the best,
Robert

**Pull request merged**
