### PR TITLE
Update look'n'feel for GlanceView

### PR DESCRIPTION
**Pull request by axl13**
- Update the Glance view to fit with better to standard widgets
- Add progress bar when the goal is set
- Display percentage of goal completion

P.S. Unfortunately standard fonts does not always match build-in widgets style. 

Screen Shot 2020-06-06 at 9 27 21 PM

Screen Shot 2020-06-06 at 9 34 49 PM

### CODE REVIEW

**Comment by pyrob2142** [comment]
Thanks for your contribution! This does indeed look a lot better and it provides more information to the user, which is always awesome. 

A few things that came to my mind after testing it:
If no goal is set an empty progress bar is displayed. Is this just for visual consistency? The widget itself uses a blue ring in this state, so I would probably either fill the bar with blue to keep it consistent with the widget or get rid of it, as it holds no information and it may be a bit demotivating to look at a progress bar that simply won't budge by design.

I'm thinking about integrating the traffic light color scheme, which the ring uses for fasts with a set goal,  into the glance view progress bar as well, so the amount of information is consistent with the widget itself.

Another thing I'm currently playing with is allowing the progress arc to "overfill" up to 200% to provide a visual representation of the overtime percentage. I think I could also integrate this easily into the bar in the glance view.

What are your thoughts about this stuff?

Again, thanks for taking the time and making this pull request! I really appreciate it and will merge it into the project later today, maybe with the aforementioned adaptations. Will be a busy Sunday for me :)

P.S.: You guys in Switzerland use "m" as an abbreviation for minutes? I was unsure about this, when I started localizing the widget, but asked around at work, as well as friends and family and here in Austria it seems that "min" is the more widespread abbreviation and the internet seems to concur. Or is it because otherwise the string won't fit below the bar?

**Comment by axl13** [comment]
Hey! 

Thank you for looking in to that. And for all the work you've done. I was looking for such widget a few weeks ago and was surprised not to see one! And yesterday I came across this project! Good job man!

Now to the comments. 
The empty bar for 'no goal' case was indeed to fill in the space. Fill it in with blue should work nicely! I'll do that. 

Agee on the 'traffic light'. I'll look in to that.

How would you like to overflow? As it is now the bar reaching full Width of the screen, but percentage on top keep counting up (and the overtime is counting). I guess we could indicate further progress with colors somehow. 

For the 'm' vs 'min' this is just to keep consistently with how Garmin does it for it's widgets in glance mode, and also to save the precious space a little. On this point, I'm not sure how useful seconds are there. On Fenix 6 the view does not refresh often enough (as on Fenix 6 Pro version), thus those look stale and taking up the precious space. I think the refresh rate is more than a minute.  May be worth to remove them completely and make the font a little bigger to 
match the rest of the styling. 

Thank you for the review and your comments! I will send another pull request shortly

IMG_20200607_103413


P.S. The Garmin's inconsistency in font type and sizes is really frustrating. OTOH, there is no "wrong" way of doing so!

**Comment by pyrob2142** [comment]
You have no idea how useful it is to see a picture of how the carousel looks on the real thing. Garmin should really up its simulator game, as all I can do regarding glances is guess-work, because my Fenix 5 isn't supporting them. 

I have pushed the overflow code to master, but I think it's easier if I just incorporate the small changes directly as I merge your code. It's not a lot that needs to be done and I just think it's easier to manage this way. I'm quite new to using git (it's my first public project) and still have to figure out a lot of things. Testing your submission without overwriting master took me a good hour of setup, because I couldn't figure out how to get Eclipse to accept two projects with the same name... Still learning how to do things properly. 

As for the seconds: I'm aware of the problem with the Fenix 6 and 6S. I could push a separate glance view for those devices, but I figure it holds more information in the static way it is currently, than disabling the feature entirely for those watches as Garmin doesn't guarantee a fixed update interval with them. I'm also currently in the process of creating a setting that lets the user decide if they want to disable seconds altogether and switch to updates every minute to reduce the power draw of the widget.

**Comment by pyrob2142** [comment]
Just a little update: I've merged your changes and incorporated the ideas discussed above. Seems to work fine, now I just need to update the localization side of things to match with the new string resource and do some house keeping. 

That was a crazy good idea you had, thank you! I think the next update will drop latest somewhere around Wednesday, as I want to finish the other improvements first and deploy everything at once in order to keep updates fairly unobtrusive to the users. Please let me know how and where I should credit you, as I think pretty much no one will look at the commit history to notice your effort, which would be sad. I was thinking I could mention you in the What's new section of the store page, if you want?

**Comment by axl13** [comment]
Thats awesome! Thank you! 

I really like the Glance feature of Fenix. Very useful and informative way to get an overview. 

I have an optional view in works: 
A67E1451

What do you think? A little more colors. What about the seconds, you wanna keep them?

```  // Progress Bar
                // The progress will progress through the colors
                bar_color = Graphics.COLOR_RED;
                dc.setColor(bar_color, Graphics.COLOR_BLACK);
                dc.fillRectangle(0, center_y - 3, dc.getWidth() * progress, 7);
                if (percent > streak_reset_threshold) {
                    bar_color = Graphics.COLOR_YELLOW;
                    dc.setColor(bar_color, Graphics.COLOR_BLACK);
                    dc.fillRectangle(dc.getWidth() * streak_reset_threshold / 100, center_y - 3, dc.getWidth() * progress, 7);
                } if (percent > streak_inc_threshold) {
                    bar_color = Graphics.COLOR_GREEN;
                    dc.setColor(bar_color, Graphics.COLOR_BLACK);
                    dc.fillRectangle(dc.getWidth() * streak_inc_threshold / 100, center_y - 3, dc.getWidth() * progress, 7);
                }
```
Screen Shot 2020-06-07 at 4 24 51 PM
Screen Shot 2020-06-07 at 4 33 31 PM



re: credits. Would be nice, no pressure :) I'll help out with localizing the stuff for Ukrainian and Russian. Also an option to manually put BMR could be helpful too. I have mine 'estimated' to

**Comment by pyrob2142** [comment]
So basically the colors would stack until they reach 100%, that looks cool. I'm just not sure how to integrate the overtime into the color scheme. Right now I simply overwrite the original bar with dark green and fill it again with green to keep the semantics of the colors intuitive. Red and green have darker versions available, for yellow we could only use orange to make it darker and then there is still the question of which color to use for the new fill from 100% to 200%. 
I was already thinking about adding little markers (think of minute markers on analogue watch faces) to the widget, so that a user can visualize when a mile stone (yellow, green thresholds) will be reached, so that stacked representation would also look pretty great for the ring itself. 
What I'm thinking is that from 100% to 200% there are no mile stones to reach anymore because technically the fast is already complete and I just want to show the user how much extra effort he's putting in. So a single color for the overfill would be best. What do you think about just sticking with green for the overfill?

As for the seconds: My plan is currently to add a user setting in the next days so they can enable a power save mode, which will only update every minute. With this setting enabled the seconds would be gone from the glance view as well and using device identifiers the same code could be used to disable them for the glance view on the Fenix 6 and 6S. I would like to keep displaying them by default on devices that have the processing power to update once per second. 

The option for the manual BMR entry is a great idea for people who have professional measurements taken! I've put it on the to do list, sounds simple enough :)

Thanks for the translations! Just fill in the Google sheet linked in the readme and the corresponding xml files can be generated using the python script. I already updated it to incorporate the new string for the glance view, so that should work fine, but I would probably wait a bit as all these settings / properties will need new strings as well.

**Pull request merged**
